Core concepts plus styling
JAndresHJ/react-certification-2021 pull request #1
Opened 2021-07-27 19:18 UTC by JAndresHJ

2021-07-29 23:01 UTC, AlejandroSeguraWIZ requested changes
I do like your project. The structure is awesome. I just left some comments regarding the separation of concerns for each component, but overall good job!

Also, I recommend you to put the test files in a folder `__tests__`. i.e.
```
Header/
    __tests__/
         Header.test.js
```

2021-07-29 23:01 UTC, AlejandroSeguraWIZ commented on src/components/Header/Header.jsx
> +  );
This could be moved to another component like `DesktopMenu`

2021-07-29 23:01 UTC, AlejandroSeguraWIZ commented on src/components/Header/Header.jsx
> +  );
This could be moved to another component like `MobileMenu`

2021-07-29 23:01 UTC, AlejandroSeguraWIZ commented on src/components/Header/Header.jsx
> +      {renderMenu}
This could be replaced by:
```
<DesktopMenu {...someProps} />
<MobileMenu {...otherProps} />
```

2021-07-29 23:01 UTC, AlejandroSeguraWIZ commented on src/components/Header/Header.jsx
> +          </div>
This could be another component like `DesktopActionsHeader`

2021-07-29 23:01 UTC, AlejandroSeguraWIZ commented on src/components/Header/Header.jsx
> +          </div>
This could be another component like `MobileActionsHeader`

2021-07-29 23:01 UTC, AlejandroSeguraWIZ commented on src/components/Header/Header.jsx
> +  return (
I think this component is way too long. It should be split into different pieces to make them more granular, readable, and maintainable.
A possibility could be turning the component into the next structure:
```
<Header>
     <BurgerMenu />
     <SearchInput />
     <DesktopActions />
     <MobileActions />
</Header>
```

2021-07-29 23:01 UTC, AlejandroSeguraWIZ commented on src/components/Videos/Videos.js
> +const Videos = () => {
Probably a better name for this component could be `VideoList`

2021-07-30 15:27 UTC, JAndresHJ commented
Hi @AlejandroSeguraWIZ many thanks for the review! :smiley: I have addressed your comments, you were right, that header component definitely needed to be splitted.

2021-08-13 17:47 UTC, AlejandroSeguraWIZ approved these changes

2021-08-19 21:13 UTC, merged