Hooks
JAndresHJ/react-certification-2021 pull request #2
Opened 2021-08-03 03:36 UTC by JAndresHJ

## Code coverage

![test-coverage](https://user-images.githubusercontent.com/39096718/127953610-b2d57a9e-38e7-494b-84af-5bbc42b81902.PNG)

2021-08-13 17:08 UTC, AlejandroSeguraWIZ requested changes
You're still missing the `Router` to enable moving from page to page to play each video

2021-08-13 17:08 UTC, AlejandroSeguraWIZ commented on src/components/Header/DesktopMenu/DesktopMenu.js
> +  const [isDarkMode, setIsDarkedMode] = useState(false);
For the sake of consistency, this may be: `const [isDarkMode, setIsDarkMode]`

2021-08-13 17:08 UTC, AlejandroSeguraWIZ commented on src/components/Header/MobileMenu/MobileMenu.js
> +  );
Move this to another component. i.e. `MobileMenu`; and pass the necessary props to the component

2021-08-13 17:08 UTC, AlejandroSeguraWIZ commented on src/hooks/useVideos.js
> +export default useVideos;
Good job ❤️

2021-08-19 22:52 UTC, JAndresHJ commented
Thanks for the review @AlejandroSeguraWIZ :) I have refactored the Mobile Menu. I'm going to implement the `Router` on the final deliverable since is part of its requirements.

2021-08-21 15:52 UTC, merged